### ISSUE TITLE
Add logging instead of print statements everywhere

### ISSUE THREAD

**Issue by damoster** [damoster/royale_clan_card_level_ranker_bot#10]
Use the python `logging` module to do proper logging instead of print statements everywhere. 

Also add a traceId so can correlate the log messages from a traced transaction https://documentation.solarwinds.com/en/success_center/appoptics/content/kb/apm_tracing/python/context-log.htm

Save the logs to a file as opposed to printing to console. Have separate files per month (should be pretty low usage/logging so no need to split daily / weekly)

See:
- https://docs.python.org/3/howto/logging.html
- https://www.loggly.com/ultimate-guide/python-logging-basics/

**Comment by josephwccheng** [comment]
Got help from 

https://gist.github.com/EvieePy/7822af90858ef65012ea500bcecf1612?fbclid=IwAR19Eib8D8v3z83Fdi5Pq8RY5XXlnvVOMcpZvihk8-7uCoNuPFBvFzXfXPY

and 

https://gist.github.com/PikalaxALT/c2c13a437fbb5387d9c28aeb8a261cd7
