### ISSUE TITLE
Update ranking to group lvl13/14 together

### ISSUE THREAD

**Issue by damoster** [damoster/royale_clan_card_level_ranker_bot#42]
Changes to do:
- Update sort `comparator function` to combine lvl13 and lvl14 cards when comparing two players
- Update ranking test. I used player tags and looked up some peeps in clan who were higher than you for all card counts, but not for buildings etc. Please try keep this test case. Remove "Goku" and replace with other players who have similar test case if possible
- Update output to still show lvl14 and lvl13 cards... but maybe do this for before and after:

Before:
#lvl14,13,12,11
3, 32, 20, 11

After:
#lvl (14,13),12,11
(3, 32), 20, 11

Make sure to:
- Add `#42` as prefix in your commit messages so that it links to this ticket
- Open PR and put closes `#42` in the PR description

**Comment by josephwccheng** [comment]
Test case;
Pick three players 1,2,3 and rank them in the following order:
No filters -> 1,2,3
Troops -> 1,2,3
Spells -> 1,3,2
Building -> 1,3,2

1st player:　zepol
2nd player:  joseph
3rd player:  drizzle
