### ISSUE TITLE
Revisit setup of main.py

### ISSUE THREAD

**Issue by damoster** [damoster/royale_clan_card_level_ranker_bot#45]
Double check if the current setup of main.py is correct (and whether or not it's wonky setup as below etc is the reason why it sometimes just has random concurrency issues

```
def main():
    async def some_func():
```

**Comment by josephwccheng** [comment]
Created a new class specifically for discord bot.
Instead of using "from discord.ext.commands import Bot" class I just use "self.bot = commands.Bot(command_prefix="!", description="!bothelp"
