### ISSUE TITLE
!ausclanwar command to find which players have/haven't been active in war in past 4 weeks

### ISSUE THREAD

**Issue by damoster** [damoster/royale_clan_card_level_ranker_bot#47]
Can use the following endpoint to determine player participation over recent 4 weeks.
```
GET /clans/{clanTag}/riverracelog
```
Note: endpoint is from official Royale API https://developer.clashroyale.com/ and seems to only return data for completed war week instead of current war week (double check this)

### Criteria for "actively participating in war":
1. Been in clan for 4 weeks
2. Have done at least 3 of 4 war days per week (i.e. used 4 decks 3 times = 12 battles. At a minimum if they lose every battle that's NOT a boat attack, that would be 12 * 100 = 1200 fame. Use `fame` instead of `decksUsed` since can only get `fame` on war days, whereas `decksUsed` include practise days. ~~[TBD - check slack chat for final decision] Have done at least 3 of 4 war days per week (i.e. used 4 decks 3 times = 12 `decksUsed` that week)~~

Note: Discuss with @damoster , we might be able to make this limit dynamic. Looks like API response shows season start time, and what time a clan finishes the race. So we could calc how many war days it took for us to win (or lose) and set a required battle limit accordingly.... (Though maybe lets make that a separate issue/PR and try to keep this one as simple/quick as possible)

### Output requirements
- "X" if there was any week which had fame less than 1200. "/" if all weeks were above minimum fame.
- Can call `GET /clans/{clanTag}/members` to get the roles
- Order output by Ave fame per week, have the following columns (Or maybe order by min Fame in any of past 4 Weeks of each player)
```
WarActive | PlayerName | Role     |  Past4WeekFameCount  |
----------+------------+----------+----------------------+
    /     | SomeDude   | Member   |  2700,2400,2500,2600 |
    /     | D-drizzle  | Co-leader|  1600,1500,2000,1900 |
    X     | JoeMama    | Elder    |  2000,1400, 900,1000 |
    X     | JoeDad     | Elder    |  1000, 200,1400,1800 |
```
- Make sure spacing is nice for the `Past4WeekFameCount`, i.e. even if number is 3 digits, make it expand to take up 4 spaces. There's examples online and how @damoster has done it for existing command outputs (have a look)
- I know there's a size limit on output for urls, so maybe for now, just use the letters "/" and "X". Can look into icons later in a separate issue/PR, I saw deckshoppro.com bot doing this
![image](https://user-images.githubusercontent.com/18656129/147044077-666d55f7-3518-4062-a504-cc215902a5ea.png)

If showing entire clan exceeds message limit, then we should ONLY show: 
1. Elder's who HAVE NOT been "actively participating in war"
2. Member's who HAVE been "actively participating in war"

### How to split up work
Split this work into 3 separate sub-issues or 3 separate PRs:
1. Tests + Function/class to process output from `GET /clans/{clanTag}/riverracelog` into a data structure ready for final output requirements. Btw, I know we've been using dictionaries the whole time, but can you use a list of dataclasses instead? https://docs.python.org/3/library/dataclasses.html
2. API call to `GET /clans/{clanTag}/riverracelog`
3. Add discord bot command. Lets call it `!ausclanwar` for ausclan specific, and `!waractive [clantag]` for any clan

**Comment by josephwccheng** [comment]
GET /clans/{clanTag}/members returns a list of "items" of following example:

Problem: what if the member left or only joined recently?


{
      "tag": "#8VUG0GQRY",
      "name": "joseph",
      "role": "coLeader",
      "lastSeen": "20211226T044544.000Z",
      "expLevel": 14,
      "trophies": 6393,
      "arena": {
        "id": 54000016,
        "name": "Master II"
      },
      "clanRank": 1,
      "previousClanRank": 1,
      "donations": 468,
      "donationsReceived": 360,
      "clanChestPoints": 0
}

**Comment by josephwccheng** [comment]
https://api.clashroyale.com/v1/clans/%239GULPJ9L/currentriverrace

Might be required for latest info as well
