### ISSUE TITLE
Make ranking based on troops only

### ISSUE THREAD

**Issue by damoster** [damoster/royale_clan_card_level_ranker_bot#5]
Add an enum argument to specify what to rank on. E.g.

`!membercardsranked 9GULPJ9L troops`

Would rank based on troop cards only. I.e. exclude spells/buildings. 

Might need to hardcode a lookup dict for what card is what card type. Doesn't look like royale API actually distinguishes what type each card is. But double check if that's actually the case https://developer.clashroyale.com/#/documentation

Some format ideas
```
# card_level_counts = { 13: { 'totalCount': 'spellCount': x, 'buildingCount': y, 'troopCount': z }, etc. }
# OR
# card_level_counts = { "totalCount": {13: 22, 12: 14, etc.}, "troopCount": {13: 12, 12: 10, etc.}, etc.}
```

**Comment by josephwccheng** [comment]
> card_level_counts = { "totalCount": {13: 22, 12: 14, etc.}, "troopCount": {13: 12, 12: 10, etc.}, etc.}

I am going to go with this approach

**Comment by josephwccheng** [comment]
adding file in resources/data/card_types.json with the following schema to perform the filter

{
  2600000: 'troop', # Knight
  2600001: 'troop', # Archers
  ...
  28000002: 'spell', # Rage
}
